import { Inter } from "next/font/google"
import type { Metadata } from "next"

import { SocketProvider } from "@/components/providers"
import Navbar from "@/components/Navbar"
import { cn } from "@/lib/utils"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark min-h-screen")}>
        <SocketProvider>
          <Navbar className="absolute bg-gray-800" />
          {children}
        </SocketProvider>
      </body>
    </html>
  )
}
