import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cookies } from "next/headers"

import { readFileSync } from "fs"
import path from "path"

import Navbar from "@/components/Navbar"
import { SocketProvider } from "@/components/providers"

import { cn } from "@/lib/utils"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

function getRandomAnimalName() {
  const animals = readFileSync(
    path.resolve(process.cwd(), "public/animals.txt"),
    "utf-8",
  ).split("\n")

  const animal = animals[Math.floor(Math.random() * animals.length)]
    .split(" ")
    .at(-1)!

  return `Anonymous ${animal}`
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const name = cookies().get("name")?.value ?? getRandomAnimalName()

  return (
    <html lang="en">
      <body className={cn(inter.className, "dark h-screen")}>
        <SocketProvider name={name}>
          <Navbar className="absolute bg-gray-800" name={name} />
          {children}
        </SocketProvider>
      </body>
    </html>
  )
}
